import type { NextPage } from "next"
import Head from "next/head"
import Property from "../components/Property"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <div className="font-sans text-3xl underline">Home Page</div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Property />
      </main>
    </div>
  )
}

export default Home
